name: NodeJS with Webpack Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./2do_be

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run pretty
      - run: npm run pretty_test
      - run: npm run jest_test
      
